global using Microsoft.EntityFrameworkCore;
global using Mapster;
global using TimeTracker.Shared.Entities;
global using TimeTracker.Web.Data;
global using TimeTracker.Shared.Exceptions;
global using TimeTracker.Contracts.Features.TimeEntries;
global using TimeTracker.Contracts.Features.Projects;
global using TimeTracker.Contracts.Features.Clients;
global using TimeTracker.Web.Features.AwardRate;
